### ISSUE TITLE
Bấm gửi OTP nhưng nhận về 2 tin nhắn cùng 1 lúc

### ISSUE THREAD

**Issue by nath2k2k** [toandqhe140594/FSMIS#253]
Hiện tại tôi test ở trang "Đăng ký" và "Quên mật khẩu", thì bấm tiếp tục nó gửi về 2 tin nhắn OTP cùng 1 lúc, chạy thử function trên Postman nó chỉ gửi về 1.

![image](https://user-images.githubusercontent.com/51410487/144441474-6e1d735a-920b-4671-9b04-a10f4d0d19ab.png)

**Comment by TuesdayTaco71** [comment]
Đã fix 6d7edec1250ce19eaa7af0ac13fb9dfff86b52e0
